let qs=[],i=0,ans=[],marked=[],sec=1200,timer;const $=x=>document.getElementById(x);
function show(p){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(p).classList.remove("hidden");document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===p));if(p==="mistakes")mistakes();if(p==="progress")progress()}
fetch("data/part5.json").then(r=>r.json()).then(d=>{qs=d;parts()});
function parts(){let n=["Photographs","Question-Response","Conversations","Talks","Incomplete Sentences","Text Completion","Reading Comprehension"];$("parts").innerHTML=n.map((x,j)=>`<div class="part"><span class="tag">${j<4?"LISTENING":"READING"}</span><h3>Part ${j+1}</h3><p class="muted">${x}</p><button class="secondary" ${j===4?'onclick="start()"':''}>${j===4?"Start Practice":"Coming soon"}</button></div>`).join("")}
function start(){show("practice");i=0;ans=Array(qs.length).fill(null);marked=Array(qs.length).fill(false);sec=1200;clearInterval(timer);timer=setInterval(()=>{sec--;clock();if(sec<=0){clearInterval(timer);submit()}},1000);draw()}
function clock(){let m=Math.floor(sec/60),s=sec%60;$("timer").textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}
function draw(){let q=qs[i];$("qnum").textContent=`Question ${i+1} of ${qs.length}`;$("qtext").textContent=q.question;$("choices").innerHTML=q.options.map((x,j)=>`<button class="choice ${ans[i]===j?"selected":""}" onclick="pick(${j})">(${String.fromCharCode(65+j)}) ${x}</button>`).join("");$("qprogress").style.width=((i+1)/qs.length*100)+"%";$("prev").disabled=i===0;$("next").textContent=i===qs.length-1?"Submit Test":"Next";$("mark").textContent=marked[i]?"Unmark":"Mark for Review";$("numbers").innerHTML=qs.map((_,j)=>`<button class="${ans[j]!==null?"answered ":""}${marked[j]?"marked":""}" onclick="jump(${j})">${j+1}</button>`).join("");clock()}
function pick(x){ans[i]=x;draw()}function jump(x){i=x;draw()}$("prev").onclick=()=>{if(i){i--;draw()}};$("next").onclick=()=>i<qs.length-1?(i++,draw()):submit();$("mark").onclick=()=>{marked[i]=!marked[i];draw()};
function submit(){clearInterval(timer);let c=ans.filter((a,j)=>a===qs[j].answer).length,u=ans.filter(a=>a===null).length,acc=Math.round(c/qs.length*100),score=Math.round(300+acc*4);let r={date:Date.now(),correct:c,total:qs.length,unanswered:u,acc,score,answers:[...ans]};let all=JSON.parse(localStorage.getItem("results")||"[]");all.push(r);localStorage.setItem("results",JSON.stringify(all));localStorage.setItem("lastAnswers",JSON.stringify(ans));showResult(r)}
function showResult(r){show("result");$("result").innerHTML=`<div class="hero"><span class="tag">TEST COMPLETE</span><h1>Your Part 5 Result</h1><div class="result">${r.score} / 990</div><p class="muted">${r.correct}/${r.total} correct · ${r.acc}% accuracy · ${r.unanswered} unanswered</p><button class="primary" onclick="review()">Review Answers</button> <button class="secondary" onclick="start()">Try Again</button></div>`}
function review(){show("review");$("review").innerHTML=`<div class="hero"><span class="tag">ANSWER REVIEW</span><h1>Review your answers</h1></div>`+qs.map((q,j)=>`<div class="panel review"><b>Question ${j+1}</b><h3>${q.question}</h3><p>${ans[j]===q.answer?"<span class='accent'>✓ Correct</span>":"<span style='color:#c83d55'>✗ Incorrect</span>"}</p><p>Your answer: <b>${ans[j]===null?"Unanswered":String.fromCharCode(65+ans[j])+". "+q.options[ans[j]]}</b></p><p>Correct answer: <b>${String.fromCharCode(65+q.answer)}. ${q.options[q.answer]}</b></p><p class="muted"><b>Explanation:</b> ${q.explanation}<br><b>Tiếng Việt:</b> ${q.vi}<br><b>Grammar:</b> ${q.grammar}</p></div>`).join("")}
function mistakes(){let a=JSON.parse(localStorage.getItem("results")||"[]");$("mistakes").innerHTML='<div class="panel"><h3>Wrong-answer review</h3><p class="muted">After each test, review incorrect and unanswered questions from the latest attempt.</p></div>'}
function progress(){let a=JSON.parse(localStorage.getItem("results")||"[]");$("progressBox").innerHTML=`<div class="stats"><div class="stat"><span class="muted">Best score</span><b>${a.length?Math.max(...a.map(x=>x.score)):"—"}</b></div><div class="stat"><span class="muted">Average accuracy</span><b>${a.length?Math.round(a.reduce((s,x)=>s+x.acc,0)/a.length)+"%":"—"}</b></div><div class="stat"><span class="muted">Tests</span><b>${a.length}</b></div><div class="stat"><span class="muted">Target</span><b>600+</b></div></div>`}
$("theme").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("dark",document.body.classList.contains("dark"))};if(localStorage.getItem("dark")==="true")document.body.classList.add("dark");document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>show(b.dataset.page));
